{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_set( $attribute_base )|not}
  {def $attribute_base = 'ContentObjectAttribute'}
{/if}
{* Make sure to normalize floats from db  *}
{def $latitude  = $attribute.content.latitude|explode(',')|implode('.')
     $longitude = $attribute.content.longitude|explode(',')|implode('.')}
<div class="block">

<div class="element">
{run-once}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
            integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
            crossorigin=""></script><script type="text/javascript">
{literal}
function eZLeafletLocation_MapControl( attributeId, latLongAttributeBase )
{
    var mapid = 'ezleaflet-map-' + attributeId,
        latid  = 'ezcoa-' + latLongAttributeBase + '_latitude',
        longid = 'ezcoa-' + latLongAttributeBase + '_longitude',
        $longIdEl = $("#"+longid),
        $latIdEl = $("#"+latid);
    var geocoder = null,
        addressid = 'ezleaflet-address-' + attributeId;

    var marker = {};

    var map = L.map(mapid, {
        zoomControl: false
    });

    L.control.zoom({ position: 'bottomright' }).addTo(map);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        minZoom: 1,
        maxZoom: 100
    }).addTo(map);

    var updateAll = function ( position )
    {
        updateMap(position);
        updateLatLngFields(position);
        updateAddress(position.lat + "," + position.lng);
    };

    var updateMapOnClick = function (e) {
        updateAll(e.latlng);
    };

    var updateMap = function (position) {
        if (marker != undefined) {
            map.removeLayer(marker);
        }
        map.setView(position, map.getZoom());

        marker = L.marker( position );
        marker.addTo(map);
    };


    var Geocode = function( value, callback ) {
        return $.get(
                location.protocol + '//nominatim.openstreetmap.org/?addressdetails=1&q='+value+'&format=json&limit=1',
                callback
        );
    };

    var updateAddress = function(value) {
        Geocode(value,function(data){
            console.log("geocoding...: "+ value);
            document.getElementById( addressid ).value = data[0].display_name;
        });

    };

    var findAddress = function()
    {
        var address = document.getElementById( addressid ).value;
        Geocode(address, function(data){
            var location = {};
            location.lat = data[0].lat;
            location.lng = data[0].lon;
            updateMap(location);
            updateLatLngFields(location);
            document.getElementById( addressid ).value = data[0].display_name;
        });


    };

    var updateLatLngFields = function( position )
    {
        document.getElementById(latid).value = position.lat;
        document.getElementById(longid).value = position.lng;
        document.getElementById( 'ezleaflet-restore-button-' + attributeId ).disabled = false;
        document.getElementById( 'ezleaflet-restore-button-' + attributeId ).className = 'button';
    };

    var restoretLatLngFields = function()
    {
        document.getElementById( latid ).value     = document.getElementById('ezleaflet_hidden_latitude_' + attributeId ).value;
        document.getElementById( longid ).value    = document.getElementById('ezleaflet_hidden_longitude_' + attributeId ).value;
        document.getElementById( addressid ).value = document.getElementById('ezleaflet_hidden_address_' + attributeId ).value;
        if ( document.getElementById( latid ).value && document.getElementById( latid ).value != 0 )
        {
            var pos = {};
            pos.lat = document.getElementById( latid ).value;
            pos.lng = document.getElementById( longid ).value;
            updateAll(pos);
        }
        document.getElementById( 'ezleaflet-restore-button-' + attributeId ).disabled = true;
        document.getElementById( 'ezleaflet-restore-button-' + attributeId ).className = 'button-disabled';
        return false;
    };

    var getUserPosition = function()
    {
        navigator.geolocation.getCurrentPosition( function( position )
        {
            var location = '',
                pos = {};

            pos.lat = position.coords.latitude;
            pos.lng = position.coords.longitude;

            if ( navigator.geolocation.type == 'Gears' && position.gearsAddress )
                location = [position.gearsAddress.city, position.gearsAddress.region, position.gearsAddress.country].join(', ');
            else if ( navigator.geolocation.type == 'ClientLocation' )
                location = [position.address.city, position.address.region, position.address.country].join(', ');

            document.getElementById( addressid ).value = location;

            updateAll( pos );
        },
        function( e )
        {
            alert( 'Could not get your location, error was: ' + e.message );
        },
        { 'gearsRequestAddress': true });
    };

    if ( document.getElementById( latid ).value && document.getElementById( latid ).value != 0 )
    {
        var pos = {};
        pos.lat = document.getElementById( latid ).value;
        pos.lng = document.getElementById( longid ).value;
        map.setZoom(13);
        updateAll(pos);
    }else {
        map.setView([0,0], 1);
    }

    map.on('click', updateMapOnClick);
    document.getElementById( 'ezleaflet-address-button-' + attributeId ).onclick = findAddress;
    document.getElementById( 'ezleaflet-restore-button-' + attributeId ).onclick = restoretLatLngFields;

    if ( navigator.geolocation )
    {
        document.getElementById( 'ezleaflet-mylocation-button-' + attributeId ).onclick = getUserPosition;
        document.getElementById( 'ezleaflet-mylocation-button-' + attributeId ).className = 'button';
        document.getElementById( 'ezleaflet-mylocation-button-' + attributeId ).disabled = false;
    }

    $latIdEl.change( function(){
        var pos = {};
        if($(this).val() && $longIdEl.val()){
            pos.lat = $(this).val();
            pos.lng = $longIdEl.val();
            pos.lat = (+pos.lat).toFixed(7);
            pos.lng = (+pos.lng).toFixed(7);
            updateMap(pos);
            updateAddress(pos.lat + "," + pos.lng);
        }
    });

    $longIdEl.change( function(){
        var pos = {};
        if($(this).val() && $latIdEl.val()){
            pos.lng = $(this).val();
            pos.lat = $latIdEl.val();
            pos.lat = (+pos.lat).toFixed(7);
            pos.lng = (+pos.lng).toFixed(7);
            updateMap(pos);
            updateAddress(pos.lat + "," + pos.lng);
        }
    });
}

{/literal}
</script>
{/run-once}

<script type="text/javascript">
<!--

if ( window.addEventListener )
    window.addEventListener('load', function(){ldelim} eZLeafletLocation_MapControl( {$attribute.id}, "{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" ) {rdelim}, false);
else if ( window.attachEvent )
    window.attachEvent('onload', function(){ldelim} eZLeafletLocation_MapControl( {$attribute.id}, "{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" ) {rdelim} );

-->
</script>

    <input type="text" id="ezleaflet-address-{$attribute.id}" size="62" name="{$attribute_base}_data_leafletlocation_address_{$attribute.id}" value="{$attribute.content.address}"/>
    <input class="button" type="button" id="ezleaflet-address-button-{$attribute.id}" value="{'Find address'|i18n('extension/ezleafletlocation/datatype')}"/>
    <input class="button-disabled" type="button" id="ezleaflet-restore-button-{$attribute.id}" value="{'Restore'|i18n('extension/ezleafletlocation/datatype')}" onclick="javascript:void( null ); return false" disabled="disabled"  title="{'Restores location and address values to what it was on page load.'|i18n('extension/ezleafletlocation/datatype')}" />

    <input id="ezleaflet_hidden_address_{$attribute.id}" type="hidden" name="ezleaflet_hidden_address_{$attribute.id}" value="{$attribute.content.address}" disabled="disabled" />
    <input id="ezleaflet_hidden_latitude_{$attribute.id}" type="hidden" name="ezleaflet_hidden_latitude_{$attribute.id}" value="{$latitude}" disabled="disabled" />
    <input id="ezleaflet_hidden_longitude_{$attribute.id}" type="hidden" name="ezleaflet_hidden_longitude_{$attribute.id}" value="{$longitude}" disabled="disabled" />
    <div id="ezleaflet-map-{$attribute.id}" style="width: 500px; height: 280px; margin-top: 2px;"></div>
</div>

<div class="element">
  <div class="block">
    <label>{'Latitude'|i18n('extension/ezleafletlocation/datatype')}:</label>
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_latitude" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_data_leafletlocation_latitude_{$attribute.id}" value="{$latitude}" />
  </div>

  <div class="block">
    <label>{'Longitude'|i18n('extension/ezleafletlocation/datatype')}:</label>
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_longitude" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_data_leafletlocation_longitude_{$attribute.id}" value="{$longitude}" />
  </div>

  <div class="block">
    <input class="button-disabled" type="button" id="ezleaflet-mylocation-button-{$attribute.id}" value="{'My current location'|i18n('extension/ezleafletlocation/datatype')}" onclick="javascript:void( null ); return false" disabled="disabled" title="{'Gets your current position if your browser support GeoLocation and you grant this website access to it! Most accurate if you have a built in gps in your Internet device! Also note that you might still have to type in address manually!'|i18n('extension/ezleafletlocation/datatype')}" />
  </div>
</div>

<div class="break"></div>
</div>
